# supported languages: "custom" (default, english) and "de" (german)
language: custom

# currency name and value config
currency:
  # currency name to use in messages
  name:
    singular: Knut
    plural: Knuts

  # number of decimal digits supported by currency value (0 for whole numbers only)
  digits: 0

  # value of individual denominations. default: emerald: 1, emerald block: 9
  denominations:
    371: 1
    264:
      value: 29
      singular: Sickle
      plural: Sickles
    388:
      value: 493
      singular: Galleon
      plural: Galleons
    133: 4437

# tax on /money pay transactions
transactiontax:
  flat: 0.0
  rate: 0.0

# balance to start an account with (purely virtual)
startingbalance:
  player: 0
  faction: 0
  town: 0
  nation: 0

# globally (dis)allow use of vault types
usevault:
  container: true
  enderchest: true
