# Loads in base potter configs
example: potter

# Gives the correct wand when the player does /wand
default_wand: randomizedpotterwand

# Disables all cast messages in chat
show_cast_messages: true

# Enables custom crafting recipes
enable_crafting: true
