# Starts the player off with no SP since we're disabling it below
sp_default: 0

# Disables the SP system in favor of AC
sp_enabled: false

# Defines custom currencies
custom_currency:
  galleon:
    max: 9999
    default: 0
    icon: gold_nugget
  ac:
    max: 9999
    default: 0
    icon: diamond_axe{CustomModelData:402}
  cc:
    max: 9999
    default: 0
    icon: diamond_axe{CustomModelData:403}
