# Sets the PotterPlus resource pack.
resource_pack: "https://download.mc-packs.net/pack/7f276c35244d486c4de10bf5c9e119f944d3b1ae.zip"
# Auto-apply the resource pack on login.
resource_pack_default_auto: true
