# Sets the BetterPotter resource pack.
resource_pack: "https://download.mc-packs.net/pack/a952782b22c2041555a45933dae9ebbc09f35451.zip"
# Auto-apply the resource pack on login.
resource_pack_default_auto: true
