base_wand:
  # When the drop key is pressed while holding the wand, open the spell
  # inventory
  drop: toggle
  # When left clicking while holding the wand, cast the active spell
  left_click: cast
  # When right clicking while holding the wand, open the spell inventory
  right_click: toggle
  # When the swap key is pressed while holding the wand, cycle between the
  # multiple spell hotbars
  swap: cycle_hotbar

wandbox:
  enabled: false

potterwand:
  # Defines how many spell hotbars the wand will have
  hotbar_count: 2
  # Defines what spell the wand has selected by default
  active_spell: lumos
  # Defines what spells are in the wand's inventory
  spells:
    - lumos
  # Defines what mage classes can use this wand
  classes:
    - wizard
    - auror
    - darkwizard
    - professor

randomizedpotterwand:
  # Defines which icons the wand could be created from
  icon: wooden_hoe{CustomModelData:4},wooden_hoe{CustomModelData:5},wooden_hoe{CustomModelData:6}
  randomize_icon: wooden_hoe{CustomModelData:3}
  effects:
    randomize:
      - class: EffectSingle
        sound: betterpotter.swish
