base_wand:
  # When the drop key is pressed while holding the wand, open the spell
  # inventory
  drop: toggle
  # When left clicking while holding the wand, cast the active spell
  left_click: cast
  # When right clicking while holding the wand, open the spell inventory
  right_click: toggle
  # When the swap key is pressed while holding the wand, cycle between the
  # multiple spell hotbars
  swap: cycle_hotbar
  # Leave wand messages on
  quiet: 0

wandbox:
  inherit: false
  icon: wooden_hoe{CustomModelData:100}
  active_spell: open_wandbox
  lore:
    - "$description"
  spells:
    - open_wandbox
  drop: none
  left_click: none
  right_click: cast
  swap: none

potterwand:
  # Defines how many spell hotbars the wand will have
  hotbar_count: 2
  # Defines what spell the wand has selected by default
  active_spell: lumos
  # Make sure spell messages are on
  quiet: 0
  # Defines what spells are in the wand's inventory
  spells:
    - lumos
  # Defines what mage classes can use this wand
  classes:
    - wizard
    - auror
    - darkwizard
    - professor

randomizedpotterwand:
  # Defines which icons the wand could be created from
  icon: wooden_hoe{CustomModelData:1},wooden_hoe{CustomModelData:2},wooden_hoe{CustomModelData:3}
  randomize_icon: diamond_hoe{CustomModelData:138}
  effects:
    randomize:
      - sound: betterpotter.swish
        source_location: feet
        effectlib:
          class: AnimatedBall
          particle: fireworks_spark
          particle_data: 0.1
          duration: 5000
