base_wand:
  drop: toggle
  left_click: cast
  swap: cycle_hotbar

wandbox:
  enabled: false

potterwand:
  hotbar_count: 2
  icon: wood_hoe:24,wood_hoe:25,wood_hoe:26
  spells:
    - lumos
  active_spell: lumos
  classes:
    - wizard
    - auror
    - darkwizard
    - professor

randomizedpotterwand:
  icon: wood_hoe:24,wood_hoe:25,wood_hoe:26
  effects:
    randomize:
    -  class: EffectSingle
       sound: betterpotter.swish
