wands:
  ticket:
    name: "&5Wand Ticket"
    description: >-
      &dYou can trade this for your very first wand
      at a &5Wand Shop&8.
  randomizedpotterwand:
    description: "$length Inches $flex $wood with $core"
    name: "Wand"
    randomized_description: >-
      &bContains your very own wand.
      What adventures await?
    spell_instructions: >-
      &7&lWAND BASICS&8//
      &dLeft-click &5to cast spells.
      &dRight-click&8/&dDrop button &5to open and close the spell menu.
      &dSwap button &5to cycle between hotbars.
    inventory_instructions: >-
      &7&lWAND INVENTORY MANAGEMENT&8//
      &5You now know more than one spell!
      &dOpen your inventory &5to manage which spells are in your hotbar.
      &dUse number keys &5to change to the desired spell in your hotbar.
      &dPress swap &5to cycle hotbars.
    enchant_instructions: ""
    bound_instructions: ""
