spells:
  default:
    backfire: >-
      &8>> &cYour spell backfired on you!
    cast_play_message: >-
      &8>> &6$player &7cast &6$spell &7on you&8!
    fail: >-
      &8>> &cSpell failed!
    fizzle: >-
      &8>> &cYour spell fizzled!
